CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    column_id INT NOT NULL REFERENCES columns(id) ON DELETE CASCADE,
    position INT NOT NULL DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);